import type { Metadata } from "next";
import { Figtree, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBar from "./components/Sidebar";
const font = Figtree({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Spotify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <div className="flex h-screen">
          <SideBar children={undefined} />
          <main className="flex-1 bg-neutral-900 rounded-xl m-3 mr-1">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
